name: TranslationsBridge
version: ${version}
main: me.siridev.translationsBridge.spigot.TranslationsBridge
api-version: '1.21'
load: STARTUP
authors: [ SirImperivm_ ]
description: Gets the automatic translations for a plugin configuration.
